services:
  activemq:
    image: rmohr/activemq:5.15.9
    ports:
      - "61616:61616" # broker (admin:adminactivemq)(amq:amq)
      - "8161:8161"   # web    http://localhost:8161/admin (admin:admin)